# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture_pokemon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_capture(object):
    def setupUi(self, capture):
        capture.setObjectName("capture")
        capture.resize(472, 366)
        self.fond_prairie = QtWidgets.QLabel(capture)
        self.fond_prairie.setGeometry(QtCore.QRect(-4, -8, 491, 381))
        self.fond_prairie.setText("")
        self.fond_prairie.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.fond_prairie.setScaledContents(True)
        self.fond_prairie.setObjectName("fond_prairie")
        self.pokeball = QtWidgets.QLabel(capture)
        self.pokeball.setGeometry(QtCore.QRect(120, 60, 211, 341))
        self.pokeball.setText("")
        self.pokeball.setPixmap(QtGui.QPixmap("interface_graphique/images/pokeball.png"))
        self.pokeball.setScaledContents(True)
        self.pokeball.setObjectName("pokeball")
        self.pokemon_capture = QtWidgets.QLabel(capture)
        self.pokemon_capture.setGeometry(QtCore.QRect(120, 130, 211, 161))
        self.pokemon_capture.setText("")
        self.pokemon_capture.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/pokemons_finaux/face/Vulpix.png"))
        self.pokemon_capture.setScaledContents(True)
        self.pokemon_capture.setObjectName("pokemon_capture")
        self.titre = QtWidgets.QLabel(capture)
        self.titre.setGeometry(QtCore.QRect(70, 20, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titre.setFont(font)
        self.titre.setObjectName("titre")
        self.ok = QtWidgets.QPushButton(capture)
        self.ok.setGeometry(QtCore.QRect(370, 320, 75, 23))
        self.ok.setObjectName("ok")

        self.retranslateUi(capture)
        QtCore.QMetaObject.connectSlotsByName(capture)

    def retranslateUi(self, capture):
        _translate = QtCore.QCoreApplication.translate
        capture.setWindowTitle(_translate("capture", "Pokémon capturé !"))
        self.titre.setText(_translate("capture", "Nom_pokemon est capturé ! "))
        self.ok.setText(_translate("capture", "OK"))
