# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix_attaque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choix_attaque(object):
    def setupUi(self, choix_attaque):
        choix_attaque.setObjectName("choix_attaque")
        choix_attaque.resize(736, 363)
        self.centralwidget = QtWidgets.QWidget(choix_attaque)
        self.centralwidget.setObjectName("centralwidget")
        self.image_fond = QtWidgets.QLabel(self.centralwidget)
        self.image_fond.setGeometry(QtCore.QRect(-60, -10, 831, 591))
        self.image_fond.setText("")
        self.image_fond.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.image_fond.setScaledContents(True)
        self.image_fond.setObjectName("image_fond")
        self.bouton_att_spe = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_att_spe.setGeometry(QtCore.QRect(20, 60, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(20)
        self.bouton_att_spe.setFont(font)
        self.bouton_att_spe.setObjectName("bouton_att_spe")
        self.bouton_att_neutre = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_att_neutre.setGeometry(QtCore.QRect(350, 60, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(20)
        self.bouton_att_neutre.setFont(font)
        self.bouton_att_neutre.setObjectName("bouton_att_neutre")
        self.txt_degats_att_spe = QtWidgets.QLabel(self.centralwidget)
        self.txt_degats_att_spe.setGeometry(QtCore.QRect(50, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_degats_att_spe.setFont(font)
        self.txt_degats_att_spe.setAutoFillBackground(False)
        self.txt_degats_att_spe.setObjectName("txt_degats_att_spe")
        self.nbr_degat_att_spe = QtWidgets.QLabel(self.centralwidget)
        self.nbr_degat_att_spe.setGeometry(QtCore.QRect(190, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nbr_degat_att_spe.setFont(font)
        self.nbr_degat_att_spe.setObjectName("nbr_degat_att_spe")
        self.txt_degats_att_neutre = QtWidgets.QLabel(self.centralwidget)
        self.txt_degats_att_neutre.setGeometry(QtCore.QRect(370, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_degats_att_neutre.setFont(font)
        self.txt_degats_att_neutre.setAutoFillBackground(False)
        self.txt_degats_att_neutre.setObjectName("txt_degats_att_neutre")
        self.nbr_degat_att_neutre = QtWidgets.QLabel(self.centralwidget)
        self.nbr_degat_att_neutre.setGeometry(QtCore.QRect(520, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nbr_degat_att_neutre.setFont(font)
        self.nbr_degat_att_neutre.setObjectName("nbr_degat_att_neutre")
        """choix_attaque.setCentralWidget(self.centralwidget)"""
        # self.menubar = QtWidgets.QMenuBar(Dialog)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 21))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(choix_attaque)
        self.statusbar.setObjectName("statusbar")
        """choix_attaque.setStatusBar(self.statusbar)"""

        self.retranslateUi(choix_attaque)
        QtCore.QMetaObject.connectSlotsByName(choix_attaque)

    def retranslateUi(self, choix_attaque):
        _translate = QtCore.QCoreApplication.translate
        choix_attaque.setWindowTitle(_translate("choix_attaque", "Choisis ton attaque !"))
        self.bouton_att_spe.setText(_translate("choix_attaque", "Attaque spéciale"))
        self.bouton_att_neutre.setText(_translate("choix_attaque", "Attaque neutre"))
        self.txt_degats_att_spe.setText(_translate("choix_attaque", "Dégats inffligés :              HP"))
        self.nbr_degat_att_spe.setText(_translate("choix_attaque", "XX"))
        self.txt_degats_att_neutre.setText(_translate("choix_attaque", "Dégats inffligés :              HP"))
        self.nbr_degat_att_neutre.setText(_translate("choix_attaque", "XX"))
