# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix_pokemon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_choix_pokemon(object):
    def setupUi(self, Dialog_choix_pokemon):
        Dialog_choix_pokemon.setObjectName("Dialog_choix_pokemon")
        Dialog_choix_pokemon.resize(600, 386)
        self.fond_ciel_bleu = QtWidgets.QLabel(Dialog_choix_pokemon)
        self.fond_ciel_bleu.setGeometry(QtCore.QRect(-10, -20, 821, 521))
        self.fond_ciel_bleu.setText("")
        self.fond_ciel_bleu.setPixmap(QtGui.QPixmap("images/prairie_et_ciel.png"))
        self.fond_ciel_bleu.setScaledContents(True)
        self.fond_ciel_bleu.setObjectName("fond_ciel_bleu")
        self.txt_choix_pokemon = QtWidgets.QLabel(Dialog_choix_pokemon)
        self.txt_choix_pokemon.setGeometry(QtCore.QRect(20, 20, 321, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_choix_pokemon.sizePolicy().hasHeightForWidth())
        self.txt_choix_pokemon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.txt_choix_pokemon.setFont(font)
        self.txt_choix_pokemon.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.txt_choix_pokemon.setObjectName("txt_choix_pokemon")
        self.ComboBox_choix_pokemon = QtWidgets.QComboBox(Dialog_choix_pokemon)
        self.ComboBox_choix_pokemon.setGeometry(QtCore.QRect(50, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setItalic(False)
        self.ComboBox_choix_pokemon.setFont(font)
        self.ComboBox_choix_pokemon.setObjectName("ComboBox_choix_pokemon")
        self.ComboBox_choix_pokemon.addItem("")
        self.ComboBox_choix_pokemon.addItem("")
        self.ok = QtWidgets.QPushButton(Dialog_choix_pokemon)
        self.ok.setGeometry(QtCore.QRect(270, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.ok.setFont(font)
        self.ok.setObjectName("ok")
        self.image_pokemon = QtWidgets.QLabel(Dialog_choix_pokemon)
        self.image_pokemon.setGeometry(QtCore.QRect(60, 180, 181, 161))
        self.image_pokemon.setText("")
        self.image_pokemon.setPixmap(QtGui.QPixmap("images/images_pokemon/pokemons_finaux/face/Bulbasaur.png"))
        self.image_pokemon.setScaledContents(True)
        self.image_pokemon.setObjectName("image_pokemon")
        self.perso_qui_court = QtWidgets.QLabel(Dialog_choix_pokemon)
        self.perso_qui_court.setGeometry(QtCore.QRect(390, -10, 201, 371))
        self.perso_qui_court.setText("")
        self.perso_qui_court.setPixmap(QtGui.QPixmap("images/perso_attaque.png"))
        self.perso_qui_court.setScaledContents(True)
        self.perso_qui_court.setObjectName("perso_qui_court")

        self.retranslateUi(Dialog_choix_pokemon)
        QtCore.QMetaObject.connectSlotsByName(Dialog_choix_pokemon)

    def retranslateUi(self, Dialog_choix_pokemon):
        _translate = QtCore.QCoreApplication.translate
        Dialog_choix_pokemon.setWindowTitle(_translate("Dialog_choix_pokemon", "Dialog"))
        self.txt_choix_pokemon.setText(_translate("Dialog_choix_pokemon", "Choix du pokémon :"))
        self.ComboBox_choix_pokemon.setItemText(0, _translate("Dialog_choix_pokemon", "pokémon 1"))
        self.ComboBox_choix_pokemon.setItemText(1, _translate("Dialog_choix_pokemon", "pokémon 2"))
        self.ok.setText(_translate("Dialog_choix_pokemon", "OK"))
