# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debut_combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(819, 543)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_choix_pokemon = QtWidgets.QLabel(self.centralwidget)
        self.txt_choix_pokemon.setGeometry(QtCore.QRect(30, 30, 461, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_choix_pokemon.sizePolicy().hasHeightForWidth())
        self.txt_choix_pokemon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.txt_choix_pokemon.setFont(font)
        self.txt_choix_pokemon.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.txt_choix_pokemon.setObjectName("txt_choix_pokemon")
        self.choix_pokemon = QtWidgets.QComboBox(self.centralwidget)
        self.choix_pokemon.setGeometry(QtCore.QRect(40, 160, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        font.setItalic(False)
        self.choix_pokemon.setFont(font)
        self.choix_pokemon.setObjectName("choix_pokemon")
        self.choix_pokemon.addItem("")
        self.choix_pokemon.addItem("")
        self.fuite = QtWidgets.QPushButton(self.centralwidget)
        self.fuite.setGeometry(QtCore.QRect(390, 160, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        self.fuite.setFont(font)
        self.fuite.setObjectName("fuite")
        self.image_perso = QtWidgets.QLabel(self.centralwidget)
        self.image_perso.setGeometry(QtCore.QRect(450, 0, 331, 501))
        self.image_perso.setText("")
        self.image_perso.setPixmap(QtGui.QPixmap("images/perso_entier.png"))
        self.image_perso.setScaledContents(True)
        self.image_perso.setObjectName("image_perso")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 821, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/prairie_et_ciel.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.fuite_2 = QtWidgets.QPushButton(self.centralwidget)
        self.fuite_2.setGeometry(QtCore.QRect(700, 430, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(22)
        self.fuite_2.setFont(font)
        self.fuite_2.setObjectName("fuite_2")
        self.label.raise_()
        self.txt_choix_pokemon.raise_()
        self.choix_pokemon.raise_()
        self.image_perso.raise_()
        self.fuite.raise_()
        self.fuite_2.raise_()
        Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        Dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_choix_pokemon.setText(_translate("MainWindow", "Choix du pokémon :"))
        self.choix_pokemon.setItemText(0, _translate("MainWindow", "pokémon 1"))
        self.choix_pokemon.setItemText(1, _translate("MainWindow", "pokémon 2"))
        self.fuite.setText(_translate("MainWindow", "OK"))
        self.fuite_2.setText(_translate("MainWindow", "Fuite"))
