# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecran_accueil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ecran_accueil(object):
    def setupUi(self, ecran_accueil):
        ecran_accueil.setObjectName("ecran_accueil")
        ecran_accueil.resize(800, 600)
        self.perso = QtWidgets.QLabel(ecran_accueil)
        self.perso.setGeometry(QtCore.QRect(500, 100, 281, 461))
        self.perso.setText("")
        self.perso.setPixmap(QtGui.QPixmap("interface_graphique/images/perso_entier.png"))
        self.perso.setScaledContents(True)
        self.perso.setObjectName("perso")
        self.titre_pokemon = QtWidgets.QLabel(ecran_accueil)
        self.titre_pokemon.setGeometry(QtCore.QRect(60, 20, 381, 321))
        self.titre_pokemon.setText("")
        self.titre_pokemon.setPixmap(QtGui.QPixmap("interface_graphique/images/titre_pokemon.png"))
        self.titre_pokemon.setScaledContents(True)
        self.titre_pokemon.setObjectName("titre_pokemon")
        self.play = QtWidgets.QPushButton(ecran_accueil)
        self.play.setGeometry(QtCore.QRect(100, 290, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(67)
        self.play.setFont(font)
        self.play.setAutoFillBackground(False)
        self.play.setObjectName("play")
        self.aquali = QtWidgets.QLabel(ecran_accueil)
        self.aquali.setGeometry(QtCore.QRect(80, 420, 91, 91))
        self.aquali.setAutoFillBackground(False)
        self.aquali.setText("")
        self.aquali.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/Aquali.png"))
        self.aquali.setScaledContents(True)
        self.aquali.setObjectName("aquali")
        self.jigglypuff = QtWidgets.QLabel(ecran_accueil)
        self.jigglypuff.setGeometry(QtCore.QRect(210, 420, 101, 91))
        self.jigglypuff.setText("")
        self.jigglypuff.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/jigglypuff.png"))
        self.jigglypuff.setScaledContents(True)
        self.jigglypuff.setObjectName("jigglypuff")
        self.oddish = QtWidgets.QLabel(ecran_accueil)
        self.oddish.setGeometry(QtCore.QRect(340, 410, 101, 101))
        self.oddish.setText("")
        self.oddish.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/oddish.png"))
        self.oddish.setScaledContents(True)
        self.oddish.setObjectName("oddish")
        self.fond = QtWidgets.QLabel(ecran_accueil)
        self.fond.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.fond.setText("")
        self.fond.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.fond.setScaledContents(True)
        self.fond.setObjectName("fond")
        self.fond.raise_()
        self.perso.raise_()
        self.titre_pokemon.raise_()
        self.play.raise_()
        self.aquali.raise_()
        self.jigglypuff.raise_()
        self.oddish.raise_()

        self.retranslateUi(ecran_accueil)
        QtCore.QMetaObject.connectSlotsByName(ecran_accueil)

    def retranslateUi(self, ecran_accueil):
        _translate = QtCore.QCoreApplication.translate
        ecran_accueil.setWindowTitle(_translate("ecran_accueil", "Bienvenue sur le jeu !"))
        self.play.setText(_translate("ecran_accueil", "Play"))
