# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecran_triple.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.bouton_attaque = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_attaque.setGeometry(QtCore.QRect(30, 100, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        self.bouton_attaque.setFont(font)
        self.bouton_attaque.setObjectName("bouton_attaque")
        self.bouton_changer_pokemon = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_changer_pokemon.setGeometry(QtCore.QRect(120, 180, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(26)
        self.bouton_changer_pokemon.setFont(font)
        self.bouton_changer_pokemon.setObjectName("bouton_changer_pokemon")
        self.bouton_fuir = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_fuir.setGeometry(QtCore.QRect(210, 270, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(37)
        self.bouton_fuir.setFont(font)
        self.bouton_fuir.setObjectName("bouton_fuir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 811, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/prairie_et_ciel.png"))
        self.label.setObjectName("label")
        self.perso = QtWidgets.QLabel(self.centralwidget)
        self.perso.setGeometry(QtCore.QRect(510, -20, 281, 541))
        self.perso.setText("")
        self.perso.setPixmap(QtGui.QPixmap("images/perso_attaque.png"))
        self.perso.setScaledContents(True)
        self.perso.setObjectName("perso")
        self.label.raise_()
        self.bouton_attaque.raise_()
        self.bouton_changer_pokemon.raise_()
        self.bouton_fuir.raise_()
        self.perso.raise_()
        Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouton_attaque.setText(_translate("MainWindow", "Attaque"))
        self.bouton_changer_pokemon.setText(_translate("MainWindow", "Changer de pokemon"))
        self.bouton_fuir.setText(_translate("MainWindow", "Fuir"))
