# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecran_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ecran_final(object):
    def setupUi(self, ecran_final):
        ecran_final.setObjectName("ecran_final")
        ecran_final.resize(279, 531)
        self.ciel_bleu = QtWidgets.QLabel(ecran_final)
        self.ciel_bleu.setGeometry(QtCore.QRect(-40, 0, 791, 821))
        self.ciel_bleu.setText("")
        self.ciel_bleu.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.ciel_bleu.setScaledContents(True)
        self.ciel_bleu.setObjectName("ciel_bleu")
        self.perso_final = QtWidgets.QLabel(ecran_final)
        self.perso_final.setGeometry(QtCore.QRect(0, 70, 281, 461))
        self.perso_final.setText("")
        self.perso_final.setPixmap(QtGui.QPixmap("interface_graphique/images/image_finale.png"))
        self.perso_final.setScaledContents(True)
        self.perso_final.setObjectName("perso_final")
        self.txt_bravo = QtWidgets.QLabel(ecran_final)
        self.txt_bravo.setGeometry(QtCore.QRect(80, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txt_bravo.setFont(font)
        self.txt_bravo.setObjectName("txt_bravo")
        self.txt = QtWidgets.QLabel(ecran_final)
        self.txt.setGeometry(QtCore.QRect(20, 60, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.txt.setFont(font)
        self.txt.setObjectName("txt")
        self.txt_remerciement = QtWidgets.QLabel(ecran_final)
        self.txt_remerciement.setGeometry(QtCore.QRect(60, 500, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_remerciement.setFont(font)
        self.txt_remerciement.setObjectName("txt_remerciement")

        self.retranslateUi(ecran_final)
        QtCore.QMetaObject.connectSlotsByName(ecran_final)

    def retranslateUi(self, ecran_final):
        _translate = QtCore.QCoreApplication.translate
        ecran_final.setWindowTitle(_translate("ecran_final", "Félicitations !"))
        self.txt_bravo.setText(_translate("ecran_final", "Bravo !"))
        self.txt.setText(_translate("ecran_final", "Tu les as tous capturés"))
        self.txt_remerciement.setText(_translate("ecran_final", "Merci d\'avoir joué ;)"))
