# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecran_triple.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ecran_triple(object):
    def setupUi(self, ecran_triple):
        ecran_triple.setObjectName("ecran_triple")
        ecran_triple.resize(669, 323)
        self.fond_prairie = QtWidgets.QLabel(ecran_triple)
        self.fond_prairie.setGeometry(QtCore.QRect(-80, -110, 811, 581))
        self.fond_prairie.setText("")
        self.fond_prairie.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.fond_prairie.setObjectName("fond_prairie")
        self.bouton_attaque = QtWidgets.QPushButton(ecran_triple)
        self.bouton_attaque.setGeometry(QtCore.QRect(40, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(24)
        self.bouton_attaque.setFont(font)
        self.bouton_attaque.setObjectName("bouton_attaque")
        self.bouton_changer_pokemon = QtWidgets.QPushButton(ecran_triple)
        self.bouton_changer_pokemon.setGeometry(QtCore.QRect(150, 120, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(19)
        self.bouton_changer_pokemon.setFont(font)
        self.bouton_changer_pokemon.setObjectName("bouton_changer_pokemon")
        self.bouton_fuir = QtWidgets.QPushButton(ecran_triple)
        self.bouton_fuir.setGeometry(QtCore.QRect(240, 190, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(24)
        self.bouton_fuir.setFont(font)
        self.bouton_fuir.setObjectName("bouton_fuir")
        self.perso_2 = QtWidgets.QLabel(ecran_triple)
        self.perso_2.setGeometry(QtCore.QRect(450, -90, 201, 401))
        self.perso_2.setText("")
        self.perso_2.setPixmap(QtGui.QPixmap("interface_graphique/images/perso_attaque.png"))
        self.perso_2.setScaledContents(True)
        self.perso_2.setObjectName("perso_2")

        self.retranslateUi(ecran_triple)
        QtCore.QMetaObject.connectSlotsByName(ecran_triple)

    def retranslateUi(self, ecran_triple):
        _translate = QtCore.QCoreApplication.translate
        ecran_triple.setWindowTitle(_translate("ecran_triple", "Choisis ton action !"))
        self.bouton_attaque.setText(_translate("ecran_triple", "Attaque"))
        self.bouton_changer_pokemon.setText(_translate("ecran_triple", "Changer de pokemon"))
        self.bouton_fuir.setText(_translate("ecran_triple", "Fuir"))
