# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fond_combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_arene_de_combat(object):
    def setupUi(self, Arene_de_combat):
        Arene_de_combat.setObjectName("Arene_de_combat")
        Arene_de_combat.resize(752, 509)
        self.image_fond = QtWidgets.QLabel(Arene_de_combat)
        self.image_fond.setGeometry(QtCore.QRect(0, -190, 761, 691))
        self.image_fond.setText("")
        self.image_fond.setPixmap(QtGui.QPixmap("interface_graphique/images/fond_combat.png"))
        self.image_fond.setScaledContents(True)
        self.image_fond.setObjectName("image_fond")
        self.nom_pokemon_sauvage = QtWidgets.QLabel(Arene_de_combat)
        self.nom_pokemon_sauvage.setGeometry(QtCore.QRect(40, 20, 111, 16))
        self.nom_pokemon_sauvage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nom_pokemon_sauvage.setAutoFillBackground(True)
        self.nom_pokemon_sauvage.setObjectName("nom_pokemon_sauvage")
        self.barre_vie_pokemon_sauvage = QtWidgets.QProgressBar(Arene_de_combat)
        self.barre_vie_pokemon_sauvage.setGeometry(QtCore.QRect(40, 40, 301, 31))
        self.barre_vie_pokemon_sauvage.setProperty("value", 1)
        self.barre_vie_pokemon_sauvage.setInvertedAppearance(False)
        self.barre_vie_pokemon_sauvage.setObjectName("barre_vie_pokemon_sauvage")
        self.img_mon_pokemon = QtWidgets.QLabel(Arene_de_combat)
        self.img_mon_pokemon.setGeometry(QtCore.QRect(50, 160, 261, 221))
        self.img_mon_pokemon.setText("")
        self.img_mon_pokemon.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/pokemons_finaux/dos/Bulbasaur.png"))
        self.img_mon_pokemon.setScaledContents(True)
        self.img_mon_pokemon.setObjectName("img_mon_pokemon")
        self.img_pokemon_sauvage = QtWidgets.QLabel(Arene_de_combat)
        self.img_pokemon_sauvage.setGeometry(QtCore.QRect(470, 110, 201, 151))
        self.img_pokemon_sauvage.setText("")
        self.img_pokemon_sauvage.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/pokemons_finaux/face/Vulpix.png"))
        self.img_pokemon_sauvage.setScaledContents(True)
        self.img_pokemon_sauvage.setObjectName("img_pokemon_sauvage")
        self.nom_mon_pokemon = QtWidgets.QLabel(Arene_de_combat)
        self.nom_mon_pokemon.setGeometry(QtCore.QRect(360, 320, 81, 20))
        self.nom_mon_pokemon.setMouseTracking(False)
        self.nom_mon_pokemon.setAutoFillBackground(True)
        self.nom_mon_pokemon.setObjectName("nom_mon_pokemon")
        self.barre_vie_mon_pokemon = QtWidgets.QProgressBar(Arene_de_combat)
        self.barre_vie_mon_pokemon.setGeometry(QtCore.QRect(360, 350, 301, 31))
        self.barre_vie_mon_pokemon.setProperty("value", 2)
        self.barre_vie_mon_pokemon.setInvertedAppearance(False)
        self.barre_vie_mon_pokemon.setObjectName("barre_vie_pokemon_sauvage_2")
        self.txt_descriptif = QtWidgets.QLabel(Arene_de_combat)
        self.txt_descriptif.setGeometry(QtCore.QRect(10, 420, 731, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_descriptif.setFont(font)
        self.txt_descriptif.setScaledContents(False)
        self.txt_descriptif.setWordWrap(False)
        self.txt_descriptif.setObjectName("txt_descriptif")
        self.continuer = QtWidgets.QPushButton(Arene_de_combat)
        self.continuer.setGeometry(QtCore.QRect(650, 425, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.continuer.setFont(font)
        self.continuer.setObjectName("continuer")
        
        self.retranslateUi(Arene_de_combat)
        QtCore.QMetaObject.connectSlotsByName(Arene_de_combat)

    def retranslateUi(self, Arene_de_combat):
        _translate = QtCore.QCoreApplication.translate
        Arene_de_combat.setWindowTitle(_translate("Arene_de_combat", "Arène de combat"))
        self.nom_pokemon_sauvage.setText(_translate("Arene_de_combat", " Pokémon sauvage"))
        self.barre_vie_pokemon_sauvage.setFormat(_translate("Arene_de_combat", "%v"))
        self.nom_mon_pokemon.setText(_translate("Arene_de_combat", " Mon pokémon"))
        self.barre_vie_mon_pokemon.setFormat(_translate("Arene_de_combat", "%v"))
        self.txt_descriptif.setText(_translate("Arene_de_combat", "Bulbasaur attaque !"))
        self.continuer.setText(_translate("Arene_de_combat", "Continuer"))
