# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fond_combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fond_combat(object):
    def setupUi(self, fond_combat_):
        fond_combat_.setObjectName("fond_combat_")
        fond_combat_.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(fond_combat_)
        self.centralwidget.setObjectName("centralwidget")
        self.fond_combat = QtWidgets.QLabel(self.centralwidget)
        self.fond_combat.setGeometry(QtCore.QRect(0, -8, 791, 581))
        self.fond_combat.setText("")
        self.fond_combat.setPixmap(QtGui.QPixmap("images/fond_combat.png"))
        self.fond_combat.setScaledContents(True)
        self.fond_combat.setObjectName("fond_combat")
        self.nom_pokemon_sauvage = QtWidgets.QLabel(self.centralwidget)
        self.nom_pokemon_sauvage.setGeometry(QtCore.QRect(70, 60, 111, 16))
        self.nom_pokemon_sauvage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nom_pokemon_sauvage.setAutoFillBackground(True)
        self.nom_pokemon_sauvage.setObjectName("nom_pokemon_sauvage")
        self.barre_vie_pokemon_sauvage = QtWidgets.QProgressBar(self.centralwidget)
        self.barre_vie_pokemon_sauvage.setGeometry(QtCore.QRect(70, 80, 301, 31))
        self.barre_vie_pokemon_sauvage.setProperty("value", 24)
        self.barre_vie_pokemon_sauvage.setInvertedAppearance(False)
        self.barre_vie_pokemon_sauvage.setObjectName("barre_vie_pokemon_sauvage")
        self.nom_mon_pokemon = QtWidgets.QLabel(self.centralwidget)
        self.nom_mon_pokemon.setGeometry(QtCore.QRect(470, 470, 81, 20))
        self.nom_mon_pokemon.setMouseTracking(False)
        self.nom_mon_pokemon.setAutoFillBackground(True)
        self.nom_mon_pokemon.setObjectName("nom_mon_pokemon")
        self.barre_vie_pokemon_sauvage_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.barre_vie_pokemon_sauvage_2.setGeometry(QtCore.QRect(470, 500, 301, 31))
        self.barre_vie_pokemon_sauvage_2.setProperty("value", 24)
        self.barre_vie_pokemon_sauvage_2.setInvertedAppearance(False)
        self.barre_vie_pokemon_sauvage_2.setObjectName("barre_vie_pokemon_sauvage_2")
        """fond_combat_.setCentralWidget(self.centralwidget)"""
        self.menubar = QtWidgets.QMenuBar(fond_combat_)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        """fond_combat_.setMenuBar(self.menubar)"""
        self.statusbar = QtWidgets.QStatusBar(fond_combat_)
        self.statusbar.setObjectName("statusbar")
        """fond_combat_.setStatusBar(self.statusbar)"""

        self.retranslateUi(fond_combat_)
        QtCore.QMetaObject.connectSlotsByName(fond_combat_)

    def retranslateUi(self, fond_combat_):
        _translate = QtCore.QCoreApplication.translate
        fond_combat_.setWindowTitle(_translate("fond_combat_", "Dialog"))
        self.nom_pokemon_sauvage.setText(_translate("fond_combat_", " Pokémon sauvage"))
        self.barre_vie_pokemon_sauvage.setFormat(_translate("fond_combat_", "%p%"))
        self.nom_mon_pokemon.setText(_translate("fond_combat_", " Mon pokémon"))
        self.barre_vie_pokemon_sauvage_2.setFormat(_translate("fond_combat_", "%p%"))
