# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bouton_depl_droite = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_depl_droite.setGeometry(QtCore.QRect(704, 500, 71, 23))
        self.bouton_depl_droite.setObjectName("bouton_depl_droite")
        self.bouton_depl_gauche = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_depl_gauche.setGeometry(QtCore.QRect(610, 500, 75, 23))
        self.bouton_depl_gauche.setObjectName("bouton_depl_gauche")
        self.bouton_depl_haut = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_depl_haut.setGeometry(QtCore.QRect(650, 470, 75, 23))
        self.bouton_depl_haut.setObjectName("bouton_depl_haut")
        self.bouton_depl_bas = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_depl_bas.setGeometry(QtCore.QRect(650, 530, 75, 23))
        self.bouton_depl_bas.setObjectName("bouton_depl_bas")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(660, 20, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.nom_joueur = QtWidgets.QLineEdit(self.centralwidget)
        self.nom_joueur.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.nom_joueur.setObjectName("nom_joueur")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouton_depl_droite.setText(_translate("MainWindow", "droite"))
        self.bouton_depl_gauche.setText(_translate("MainWindow", "gauche"))
        self.bouton_depl_haut.setText(_translate("MainWindow", "haut"))
        self.bouton_depl_bas.setText(_translate("MainWindow", "bas"))
        self.nom_joueur.setText(_translate("MainWindow", "Nom joueur"))
