# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix_attaque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_fond = QtWidgets.QLabel(self.centralwidget)
        self.image_fond.setGeometry(QtCore.QRect(-60, -10, 831, 591))
        self.image_fond.setText("")
        self.image_fond.setPixmap(QtGui.QPixmap("images/prairie_et_ciel.png"))
        self.image_fond.setScaledContents(True)
        self.image_fond.setObjectName("image_fond")
        self.bouton_att_spe = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_att_spe.setGeometry(QtCore.QRect(20, 60, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(20)
        self.bouton_att_spe.setFont(font)
        self.bouton_att_spe.setObjectName("bouton_att_spe")
        self.bouton_att_neutre = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_att_neutre.setGeometry(QtCore.QRect(350, 60, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(20)
        self.bouton_att_neutre.setFont(font)
        self.bouton_att_neutre.setObjectName("bouton_att_neutre")
        self.txt_degats_att_spe = QtWidgets.QLabel(self.centralwidget)
        self.txt_degats_att_spe.setGeometry(QtCore.QRect(50, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_degats_att_spe.setFont(font)
        self.txt_degats_att_spe.setAutoFillBackground(False)
        self.txt_degats_att_spe.setObjectName("txt_degats_att_spe")
        self.nbr_degat_att_spe = QtWidgets.QLabel(self.centralwidget)
        self.nbr_degat_att_spe.setGeometry(QtCore.QRect(190, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nbr_degat_att_spe.setFont(font)
        self.nbr_degat_att_spe.setObjectName("nbr_degat_att_spe")
        self.txt_degats_att_neutre = QtWidgets.QLabel(self.centralwidget)
        self.txt_degats_att_neutre.setGeometry(QtCore.QRect(370, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_degats_att_neutre.setFont(font)
        self.txt_degats_att_neutre.setAutoFillBackground(False)
        self.txt_degats_att_neutre.setObjectName("txt_degats_att_neutre")
        self.nbr_degat_att_neutre = QtWidgets.QLabel(self.centralwidget)
        self.nbr_degat_att_neutre.setGeometry(QtCore.QRect(520, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nbr_degat_att_neutre.setFont(font)
        self.nbr_degat_att_neutre.setObjectName("nbr_degat_att_neutre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouton_att_spe.setText(_translate("MainWindow", "Attaque spéciale"))
        self.bouton_att_neutre.setText(_translate("MainWindow", "Attaque neutre"))
        self.txt_degats_att_spe.setText(_translate("MainWindow", "Dégats inffligés :              HP"))
        self.nbr_degat_att_spe.setText(_translate("MainWindow", "XX"))
        self.txt_degats_att_neutre.setText(_translate("MainWindow", "Dégats inffligés :              HP"))
        self.nbr_degat_att_neutre.setText(_translate("MainWindow", "XX"))
