# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(860, 20, 118, 23))
        self.progressBar.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.nom_joueur = QtWidgets.QLineEdit(self.centralwidget)
        self.nom_joueur.setGeometry(QtCore.QRect(70, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(18)
        self.nom_joueur.setFont(font)
        self.nom_joueur.setObjectName("nom_joueur")
        self.herbe = QtWidgets.QLabel(self.centralwidget)
        self.herbe.setGeometry(QtCore.QRect(-10, -280, 1231, 1000))
        self.herbe.setToolTip("")
        self.herbe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.herbe.setAutoFillBackground(False)
        self.herbe.setText("")
        self.herbe.setPixmap(QtGui.QPixmap("images/herbe.jpg"))
        self.herbe.setScaledContents(True)
        self.herbe.setObjectName("herbe")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 250, 51, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/tete_perso.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(990, 20, 61, 21))
        self.toolButton.setObjectName("toolButton")
        self.herbe.raise_()
        self.progressBar.raise_()
        self.nom_joueur.raise_()
        self.label.raise_()
        self.toolButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nom_joueur.setText(_translate("MainWindow", "Nom joueur"))
        self.toolButton.setText(_translate("MainWindow", "..."))
