# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokedeck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pokedeck(object):
    def setupUi(self, pokedeck):
        pokedeck.setObjectName("pokedeck")
        pokedeck.resize(400, 300)
        self.perso_avec_pokemon = QtWidgets.QLabel(pokedeck)
        self.perso_avec_pokemon.setGeometry(QtCore.QRect(220, 20, 171, 201))
        self.perso_avec_pokemon.setText("")
        self.perso_avec_pokemon.setPixmap(QtGui.QPixmap("../../../tests python/images_test/perso_avec_pokemon.png"))
        self.perso_avec_pokemon.setScaledContents(True)
        self.perso_avec_pokemon.setObjectName("perso_avec_pokemon")
        self.comboBox = QtWidgets.QComboBox(pokedeck)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.fond_prairie = QtWidgets.QLabel(pokedeck)
        self.fond_prairie.setGeometry(QtCore.QRect(-4, -8, 411, 311))
        self.fond_prairie.setText("")
        self.fond_prairie.setPixmap(QtGui.QPixmap("images/prairie_et_ciel.png"))
        self.fond_prairie.setScaledContents(True)
        self.fond_prairie.setObjectName("fond_prairie")
        self.perso_avec_poke = QtWidgets.QLabel(pokedeck)
        self.perso_avec_poke.setGeometry(QtCore.QRect(220, 40, 181, 211))
        self.perso_avec_poke.setText("")
        self.perso_avec_poke.setPixmap(QtGui.QPixmap("images/perso_avec_pokemon.png"))
        self.perso_avec_poke.setScaledContents(True)
        self.perso_avec_poke.setObjectName("perso_avec_poke")
        self.image_poke = QtWidgets.QLabel(pokedeck)
        self.image_poke.setGeometry(QtCore.QRect(20, 110, 181, 161))
        self.image_poke.setText("")
        self.image_poke.setPixmap(QtGui.QPixmap("images/images_pokemon/pokemons_finaux/face/Bulbasaur.png"))
        self.image_poke.setScaledContents(True)
        self.image_poke.setObjectName("image_poke")
        self.fond_prairie.raise_()
        self.perso_avec_pokemon.raise_()
        self.comboBox.raise_()
        self.perso_avec_poke.raise_()
        self.image_poke.raise_()

        self.retranslateUi(pokedeck)
        QtCore.QMetaObject.connectSlotsByName(pokedeck)

    def retranslateUi(self, pokedeck):
        _translate = QtCore.QCoreApplication.translate
        pokedeck.setWindowTitle(_translate("pokedeck", "Dialog"))
        self.comboBox.setItemText(0, _translate("pokedeck", "Bulbasaur"))
        self.comboBox.setItemText(1, _translate("pokedeck", "Squirtle"))
        self.comboBox.setItemText(2, _translate("pokedeck", "Charmander"))
