# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokedeck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import gestion_des_pokemons.pokemons as pok
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pokedeck(object):
    def setupUi(self, pokedeck):
        pokedeck.setObjectName("pokedeck")
        pokedeck.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(pokedeck)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 191, 22))
        self.comboBox.setObjectName("comboBox")
        for k in range(len(pok.liste_pokedeck)):
            self.comboBox.addItem("")
        self.fond_prairie = QtWidgets.QLabel(pokedeck)
        self.fond_prairie.setGeometry(QtCore.QRect(-4, -8, 411, 311))
        self.fond_prairie.setText("")
        self.fond_prairie.setPixmap(QtGui.QPixmap("interface_graphique/images/prairie_et_ciel.png"))
        self.fond_prairie.setScaledContents(True)
        self.fond_prairie.setObjectName("fond_prairie")
        self.perso_avec_poke = QtWidgets.QLabel(pokedeck)
        self.perso_avec_poke.setGeometry(QtCore.QRect(220, 40, 181, 211))
        self.perso_avec_poke.setText("")
        self.perso_avec_poke.setPixmap(QtGui.QPixmap("interface_graphique/images/perso_avec_pokemon.png"))
        self.perso_avec_poke.setScaledContents(True)
        self.perso_avec_poke.setObjectName("perso_avec_poke")
        self.image_poke = QtWidgets.QLabel(pokedeck)
        self.image_poke.setGeometry(QtCore.QRect(20, 110, 181, 161))
        self.image_poke.setText("")
        self.image_poke.setPixmap(QtGui.QPixmap("interface_graphique/images/images_pokemon/pokemons_finaux/face/Bulbasaur.png"))
        self.image_poke.setScaledContents(True)
        self.image_poke.setObjectName("image_poke")
        self.txt_compteur = QtWidgets.QLabel(pokedeck)
        self.txt_compteur.setGeometry(QtCore.QRect(20, 0, 321, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_compteur.sizePolicy().hasHeightForWidth())
        self.txt_compteur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(18)
        self.txt_compteur.setFont(font)
        self.txt_compteur.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.txt_compteur.setObjectName("txt_compteur")
        self.fond_prairie.raise_()
        self.comboBox.raise_()
        self.perso_avec_poke.raise_()
        self.image_poke.raise_()
        self.txt_compteur.raise_()

        self.retranslateUi(pokedeck)
        QtCore.QMetaObject.connectSlotsByName(pokedeck)

    def retranslateUi(self, pokedeck):
        _translate = QtCore.QCoreApplication.translate
        pokedeck.setWindowTitle(_translate("pokedeck", "Pokédeck"))
        for k in range(len(pok.liste_pokedeck)):
            self.comboBox.setItemText(k, _translate("pokedeck", f"{pok.liste_pokedeck[k]}"))
        self.txt_compteur.setText(_translate("pokedeck", f"Pokémon capturés : {len(pok.liste_pokedeck)}/24"))

